apiVersion: v1
kind: Service
metadata:
  name: serve-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30300
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: serve-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 80
    nodePort: 30320
  type: NodePort
