
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: v1
kind: Service
metadata:
  name: serve-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30300
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: serve-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 80
    nodePort: 30320
  type: NodePort

